# Generated by Django 5.2.3 on 2025-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('time_taken', models.FloatField()),
                ('level_reached', models.IntegerField()),
                ('input_used', models.CharField(max_length=20)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
