# Generated by Django 5.2.3 on 2025-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('level_reached', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('input_used', models.CharField(max_length=50)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
