# Generated by Django 5.2.3 on 2025-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gamesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='played_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='input_used',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
