# Generated by Django 5.2.3 on 2025-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_played_at_gamesession_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='average_level_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
