# Generated by Django 5.2.3 on 2025-07-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gamesession_average_level_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='average_level_time',
        ),
    ]
