# Generated by Django 5.2.3 on 2025-07-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerrecord',
            old_name='level_reached',
            new_name='level_completed',
        ),
    ]
