# Generated by Django 5.2.3 on 2025-07-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_level_reached_playerrecord_level_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='level_reached',
            new_name='level_completed',
        ),
    ]
